const dtcDatabase = [
    // --- P Codes (Powertrain / Motor & Şanzıman) ---
    { code: "P0001", system: "Yakıt", desc: "<strong>Fuel Volume Regulator Control Circuit Open</strong><br>Yakıt Hacmi Regülatör Kontrol Devresi Açık" },
    { code: "P0010", system: "Motor", desc: "<strong>Camshaft Position Actuator Circuit (Bank 1)</strong><br>Eksantrik Mili Pozisyon Eyleyicisi Devresi (Bank 1)" },
    { code: "P0011", system: "Motor", desc: "<strong>Camshaft Position Timing Over-Advanced (Bank 1)</strong><br>Eksantrik Mili Zamanlaması Çok İleri (Bank 1)" },
    { code: "P0012", system: "Motor", desc: "<strong>Camshaft Position Timing Over-Retarded (Bank 1)</strong><br>Eksantrik Mili Zamanlaması Çok Geri (Bank 1)" },
    { code: "P0013", system: "Motor", desc: "<strong>Camshaft Position Actuator Circuit (Exhaust Bank 1)</strong><br>Eksantrik Mili Eyleyici Devresi (Egzoz Bank 1)" },
    { code: "P0014", system: "Motor", desc: "<strong>Camshaft Position Timing Over-Advanced (Exhaust Bank 1)</strong><br>Eksantrik Mili Zamanlaması Çok İleri (Egzoz Bank 1)" },
    { code: "P0016", system: "Motor", desc: "<strong>Crank-Cam Position Correlation (Bank 1 Sensor A)</strong><br>Krank-Eksantrik Konum Uyumsuzluğu" },
    { code: "P0030", system: "Egzoz", desc: "<strong>HO2S Heater Control Circuit (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Isıtıcı Kontrol Devresi" },
    { code: "P0031", system: "Egzoz", desc: "<strong>HO2S Heater Control Circuit Low (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Isıtıcı Devresi Düşük Voltaj" },
    { code: "P0033", system: "Turbo", desc: "<strong>Turbo Charger Bypass Valve Control Circuit</strong><br>Turbo Bypass Valfi Kontrol Devresi" },
    { code: "P0036", system: "Egzoz", desc: "<strong>HO2S Heater Control Circuit (Bank 1 Sensor 2)</strong><br>Oksijen Sensörü Isıtıcı Kontrol Devresi (Arka)" },
    { code: "P0050", system: "Egzoz", desc: "<strong>HO2S Heater Control Circuit (Bank 2 Sensor 1)</strong><br>Oksijen Sensörü Isıtıcı Devresi (Bank 2)" },
    { code: "P0056", system: "Egzoz", desc: "<strong>HO2S Heater Control Circuit (Bank 2 Sensor 2)</strong><br>Oksijen Sensörü Isıtıcı Devresi (Bank 2 Arka)" },
    { code: "P0068", system: "Hava", desc: "<strong>MAP/MAF - Throttle Position Correlation</strong><br>Hava Akış ve Gaz Kelebeği Uyumsuzluğu" },
    { code: "P0100", system: "Hava", desc: "<strong>MAF Sensor Circuit Insufficient Activity</strong><br>Kütle Hava Akış Sensörü Yetersiz Aktivite" },
    { code: "P0101", system: "Hava", desc: "<strong>MAF Sensor Performance</strong><br>Kütle Hava Akış Sensörü Performans Sorunu" },
    { code: "P0102", system: "Hava", desc: "<strong>MAF Sensor Circuit Low Frequency</strong><br>Hava Akış Sensörü Düşük Sinyal" },
    { code: "P0103", system: "Hava", desc: "<strong>MAF Sensor Circuit High Frequency</strong><br>Hava Akış Sensörü Yüksek Sinyal" },
    { code: "P0105", system: "Hava", desc: "<strong>MAP Sensor Circuit Malfunction</strong><br>Manifold Mutlak Basınç Sensörü Hatası" },
    { code: "P0106", system: "Hava", desc: "<strong>MAP/Barometric Pressure Circuit Range/Performance</strong><br>MAP Sensörü Performans Hatası" },
    { code: "P0110", system: "Hava", desc: "<strong>Intake Air Temperature Sensor Circuit</strong><br>Emme Havası Sıcaklık Sensörü Devresi" },
    { code: "P0113", system: "Hava", desc: "<strong>IAT Sensor Circuit High Voltage</strong><br>Hava Sıcaklık Sensörü Yüksek Voltaj (Açık Devre)" },
    { code: "P0115", system: "Soğutma", desc: "<strong>Engine Coolant Temperature Circuit</strong><br>Motor Su Sıcaklık Sensörü Devresi" },
    { code: "P0118", system: "Soğutma", desc: "<strong>ECT Sensor Circuit High Voltage</strong><br>Hararet Sensörü Yüksek Voltaj" },
    { code: "P0120", system: "Pedal", desc: "<strong>Throttle/Pedal Position Sensor A Circuit</strong><br>Gaz Kelebeği Konum Sensörü A Devresi" },
    { code: "P0125", system: "Soğutma", desc: "<strong>Insufficient Coolant Temp for Closed Loop</strong><br>Motor Isınmıyor (Termostat Açık)" },
    { code: "P0128", system: "Soğutma", desc: "<strong>Coolant Thermostat (Coolant Temp Below Regulating Temp)</strong><br>Soğutma Suyu Sıcaklığı Beklenenin Altında" },
    { code: "P0130", system: "Egzoz", desc: "<strong>O2 Sensor Circuit (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Devresi Arızası" },
    { code: "P0131", system: "Egzoz", desc: "<strong>O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Düşük Voltaj (Fakir Karışım)" },
    { code: "P0132", system: "Egzoz", desc: "<strong>O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Yüksek Voltaj (Zengin Karışım)" },
    { code: "P0134", system: "Egzoz", desc: "<strong>O2 Sensor Circuit No Activity (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Aktivite Yok" },
    { code: "P0135", system: "Egzoz", desc: "<strong>O2 Sensor Heater Circuit (Bank 1 Sensor 1)</strong><br>Oksijen Sensörü Isıtıcı Devresi Arızası" },
    { code: "P0136", system: "Egzoz", desc: "<strong>O2 Sensor Circuit (Bank 1 Sensor 2)</strong><br>İkinci Oksijen Sensörü Devresi Arızası" },
    { code: "P0141", system: "Egzoz", desc: "<strong>O2 Sensor Heater Circuit (Bank 1 Sensor 2)</strong><br>İkinci Oksijen Sensörü Isıtıcı Arızası" },
    { code: "P0150", system: "Egzoz", desc: "<strong>O2 Sensor Circuit (Bank 2 Sensor 1)</strong><br>Oksijen Sensörü Devresi Arızası (Bank 2)" },
    { code: "P0171", system: "Yakıt", desc: "<strong>System Too Lean (Bank 1)</strong><br>Sistem Çok Fakir (Hava Fazla/Yakıt Az)" },
    { code: "P0172", system: "Yakıt", desc: "<strong>System Too Rich (Bank 1)</strong><br>Sistem Çok Zengin (Yakıt Fazla/Hava Az)" },
    { code: "P0174", system: "Yakıt", desc: "<strong>System Too Lean (Bank 2)</strong><br>Sistem Çok Fakir (Bank 2)" },
    { code: "P0175", system: "Yakıt", desc: "<strong>System Too Rich (Bank 2)</strong><br>Sistem Çok Zengin (Bank 2)" },
    { code: "P0190", system: "Yakıt", desc: "<strong>Fuel Rail Pressure Sensor Circuit</strong><br>Yakıt Rayı Basınç Sensörü Devresi" },
    { code: "P0193", system: "Yakıt", desc: "<strong>Fuel Rail Pressure Sensor High Input</strong><br>Yakıt Basınç Sensörü Yüksek Giriş" },
    { code: "P0200", system: "Yakıt", desc: "<strong>Injector Control Circuit</strong><br>Enjektör Kontrol Devresi" },
    { code: "P0201", system: "Yakıt", desc: "<strong>Injector Circuit - Cylinder 1</strong><br>Silindir 1 Enjektör Arızası" },
    { code: "P0202", system: "Yakıt", desc: "<strong>Injector Circuit - Cylinder 2</strong><br>Silindir 2 Enjektör Arızası" },
    { code: "P0203", system: "Yakıt", desc: "<strong>Injector Circuit - Cylinder 3</strong><br>Silindir 3 Enjektör Arızası" },
    { code: "P0204", system: "Yakıt", desc: "<strong>Injector Circuit - Cylinder 4</strong><br>Silindir 4 Enjektör Arızası" },
    { code: "P0219", system: "Motor", desc: "<strong>Engine Overspeed Condition</strong><br>Motor Aşırı Devir Yaptı" },
    { code: "P0234", system: "Turbo", desc: "<strong>Turbo/Super Charger Overboost Condition</strong><br>Turbo Aşırı Basınç Durumu" },
    { code: "P0299", system: "Turbo", desc: "<strong>Turbo/Super Charger Underboost</strong><br>Turbo Düşük Basınç (Kaçak Var)" },
    { code: "P0300", system: "Ateşleme", desc: "<strong>Random/Multiple Cylinder Misfire Detected</strong><br>Rastgele Silindir Teklemesi Algılandı" },
    { code: "P0301", system: "Ateşleme", desc: "<strong>Cylinder 1 Misfire Detected</strong><br>1. Silindirde Tekleme" },
    { code: "P0302", system: "Ateşleme", desc: "<strong>Cylinder 2 Misfire Detected</strong><br>2. Silindirde Tekleme" },
    { code: "P0303", system: "Ateşleme", desc: "<strong>Cylinder 3 Misfire Detected</strong><br>3. Silindirde Tekleme" },
    { code: "P0304", system: "Ateşleme", desc: "<strong>Cylinder 4 Misfire Detected</strong><br>4. Silindirde Tekleme" },
    { code: "P0305", system: "Ateşleme", desc: "<strong>Cylinder 5 Misfire Detected</strong><br>5. Silindirde Tekleme" },
    { code: "P0306", system: "Ateşleme", desc: "<strong>Cylinder 6 Misfire Detected</strong><br>6. Silindirde Tekleme" },
    { code: "P0308", system: "Ateşleme", desc: "<strong>Cylinder 8 Misfire Detected</strong><br>8. Silindirde Tekleme" },
    { code: "P0313", system: "Ateşleme", desc: "<strong>Misfire Detected with Low Fuel</strong><br>Düşük Yakıt Seviyesinde Tekleme" },
    { code: "P0320", system: "Ateşleme", desc: "<strong>Ignition/Distributor Speed Input Circuit</strong><br>Ateşleme Hız Giriş Devresi Hatası" },
    { code: "P0325", system: "Sensör", desc: "<strong>Knock Sensor 1 Circuit (Bank 1)</strong><br>Vuruntu Sensörü Devresi" },
    { code: "P0335", system: "Sensör", desc: "<strong>Crankshaft Position Sensor A Circuit</strong><br>Krank Mili Konum Sensörü Devresi" },
    { code: "P0340", system: "Sensör", desc: "<strong>Camshaft Position Sensor Circuit</strong><br>Eksantrik Mili Konum Sensörü Devresi" },
    { code: "P0351", system: "Ateşleme", desc: "<strong>Ignition Coil A Primary/Secondary Circuit</strong><br>Ateşleme Bobini A (1) Devresi" },
    { code: "P0380", system: "Isıtma", desc: "<strong>Glow Plug/Heater Circuit A</strong><br>Kızdırma Bujisi Devresi Arızası (Dizel)" },
    { code: "P0400", system: "EGR", desc: "<strong>EGR Flow Malfunction</strong><br>EGR Akış Arızası" },
    { code: "P0401", system: "EGR", desc: "<strong>EGR Flow Insufficient Detected</strong><br>Yetersiz EGR Akışı (Tıkanıklık)" },
    { code: "P0402", system: "EGR", desc: "<strong>EGR Flow Excessive Detected</strong><br>Aşırı EGR Akışı (Açık Kalmış)" },
    { code: "P0403", system: "EGR", desc: "<strong>EGR Solenoid Control Circuit</strong><br>EGR Kontrol Valfi Devresi" },
    { code: "P0404", system: "EGR", desc: "<strong>EGR Open Position Performance</strong><br>EGR Valfi Performans Sorunu" },
    { code: "P0410", system: "Emisyon", desc: "<strong>Secondary Air Injection System</strong><br>İkincil Hava Sistemi Pompası Arızası" },
    { code: "P0420", system: "Egzoz", desc: "<strong>Catalyst System Efficiency Below Threshold (Bank 1)</strong><br>Katalizör Verimliliği Eşik Altında" },
    { code: "P0430", system: "Egzoz", desc: "<strong>Catalyst System Efficiency Below Threshold (Bank 2)</strong><br>Katalizör Verimliliği Eşik Altında (Bank 2)" },
    { code: "P0440", system: "EVAP", desc: "<strong>Evaporative Emission System</strong><br>EVAP Sistemi Genel Arıza" },
    { code: "P0441", system: "EVAP", desc: "<strong>EVAP System Incorrect Purge Flow</strong><br>EVAP Yanlış Tahliye Akışı" },
    { code: "P0442", system: "EVAP", desc: "<strong>EVAP System Small Leak Detected</strong><br>EVAP Sisteminde Küçük Kaçak" },
    { code: "P0455", system: "EVAP", desc: "<strong>EVAP System Large Leak Detected</strong><br>EVAP Sisteminde Büyük Kaçak" },
    { code: "P0480", system: "Soğutma", desc: "<strong>Cooling Fan 1 Control Circuit</strong><br>Soğutma Fanı 1 Kontrol Devresi" },
    { code: "P0500", system: "Hız", desc: "<strong>Vehicle Speed Sensor Malfunction</strong><br>Araç Hız Sensörü Arızası" },
    { code: "P0501", system: "Hız", desc: "<strong>Vehicle Speed Sensor Range/Performance</strong><br>Hız Sensörü Performans Hatası" },
    { code: "P0505", system: "Rölanti", desc: "<strong>Idle Control System Malfunction</strong><br>Rölanti Kontrol Sistem Hatası" },
    { code: "P0507", system: "Rölanti", desc: "<strong>Idle Control System RPM High</strong><br>Rölanti Beklenenden Yüksek" },
    { code: "P0520", system: "Motor", desc: "<strong>Engine Oil Pressure Sensor Circuit</strong><br>Motor Yağ Basınç Sensörü Devresi" },
    { code: "P0530", system: "Klima", desc: "<strong>A/C Refrigerant Pressure Sensor Circuit</strong><br>Klima Gaz Basınç Sensörü Devresi" },
    { code: "P0550", system: "Direksiyon", desc: "<strong>Power Steering Pressure Sensor Circuit</strong><br>Direksiyon Basınç Sensörü Devresi" },
    { code: "P0562", system: "Şarj", desc: "<strong>System Voltage Low</strong><br>Sistem Voltajı Düşük" },
    { code: "P0601", system: "ECU", desc: "<strong>Internal Control Module Memory Check Sum Error</strong><br>ECU Dahili Hafıza Hatası" },
    { code: "P0606", system: "ECU", desc: "<strong>ECM/PCM Processor</strong><br>ECU İşlemci Hatası" },
    { code: "P0620", system: "Şarj", desc: "<strong>Generator Control Circuit</strong><br>Alternatör (Şarj) Kontrol Devresi" },
    { code: "P0700", system: "Şanzıman", desc: "<strong>Transmission Control System Malfunction</strong><br>Şanzıman Kontrol Sistemi Arızası" },
    { code: "P0705", system: "Şanzıman", desc: "<strong>Transmission Range Sensor Circuit (PRNDL Input)</strong><br>Vites Konum Sensörü Arızası" },
    { code: "P0720", system: "Şanzıman", desc: "<strong>Output Speed Sensor Circuit</strong><br>Çıkış Hız Sensörü Devresi" },
    { code: "P0730", system: "Şanzıman", desc: "<strong>Incorrect Gear Ratio</strong><br>Hatalı Vites Oranı (Kaydırma/Kaçırma)" },
    { code: "P0740", system: "Şanzıman", desc: "<strong>Torque Converter Clutch Circuit</strong><br>Tork Konvertörü Kavrama Devresi" },

    // --- P1xxx Codes ---
    { code: "P1101", system: "Hava", desc: "<strong>MAF Sensor Out of Self Test Range</strong><br>MAF Sensörü Aralık Dışı (Ford/Opel)" },
    { code: "P1133", system: "Egzoz", desc: "<strong>HO2S Insufficient Switching (Sensor 1)</strong><br>Oksijen Sensörü Yetersiz Geçiş" },
    { code: "P1296", system: "Soğutma", desc: "<strong>Cooling System Malfunction (VAG)</strong><br>Soğutma Sistemi Hatası" },
    { code: "P1399", system: "Ateşleme", desc: "<strong>Random Misfire (Honda/Acura)</strong><br>Rastgele Tekleme" },
    { code: "P1403", system: "EGR", desc: "<strong>Diff Pressure Feedback Sensor Hoses Reversed</strong><br>EGR Basınç Sensör Hortumları Ters" },
    { code: "P1500", system: "Marş", desc: "<strong>Starter Signal Circuit</strong><br>Marş Sinyali Devresi" },
    { code: "P1600", system: "ECU", desc: "<strong>Loss of KAM / Battery</strong><br>ECU Batarya Kaybı" },
    { code: "P1682", system: "Elektrik", desc: "<strong>Ignition 1 Switch Circuit 2</strong><br>Kontak Anahtarı Devre Farkı (GM)" },

    // --- C Codes (Chassis / Şasi & Fren) ---
    { code: "C0000", system: "Şasi", desc: "<strong>Vehicle Speed Information Circuit Malfunction</strong><br>Araç Hız Bilgi Devresi Arızası" },
    { code: "C0035", system: "ABS", desc: "<strong>Left Front Wheel Speed Circuit Malfunction</strong><br>Sol Ön Tekerlek Hız Sensörü Arızası" },
    { code: "C0040", system: "ABS", desc: "<strong>Right Front Wheel Speed Circuit Malfunction</strong><br>Sağ Ön Tekerlek Hız Sensörü Arızası" },
    { code: "C0045", system: "ABS", desc: "<strong>Left Rear Wheel Speed Circuit Malfunction</strong><br>Sol Arka Tekerlek Hız Sensörü Arızası" },
    { code: "C0050", system: "ABS", desc: "<strong>Right Rear Wheel Speed Circuit Malfunction</strong><br>Sağ Arka Tekerlek Hız Sensörü Arızası" },
    { code: "C0060", system: "ABS", desc: "<strong>Left Front ABS Solenoid #1 Circuit Malfunction</strong><br>Sol Ön ABS Valfi Arızası" },
    { code: "C0070", system: "ABS", desc: "<strong>Right Front ABS Solenoid #1 Circuit Malfunction</strong><br>Sağ Ön ABS Valfi Arızası" },
    { code: "C0110", system: "ABS", desc: "<strong>Pump Motor Circuit Malfunction</strong><br>ABS Pompa Motoru Arızası" },
    { code: "C0121", system: "ABS", desc: "<strong>Valve Relay Circuit Malfunction</strong><br>ABS Valf Rölesi Hatası" },
    { code: "C0128", system: "Fren", desc: "<strong>Low Brake Fluid Circuit Low</strong><br>Fren Hidroliği Düşük Sinyali" },
    { code: "C0221", system: "ABS", desc: "<strong>Right Front Wheel Speed Sensor Circuit Open</strong><br>Sağ Ön Hız Sensörü Açık Devre" },
    { code: "C0235", system: "ABS", desc: "<strong>Rear Wheel Speed Signal Circuit Open</strong><br>Arka Tekerlek Hız Sinyali Açık Devre" },
    { code: "C0245", system: "ABS", desc: "<strong>Wheel Speed Sensor Frequency Error</strong><br>Tekerlek Hız Sensörü Frekans Hatası" },
    { code: "C0265", system: "ABS", desc: "<strong>EBCM Relay Circuit</strong><br>Elektronik Fren Modülü Rölesi" },
    { code: "C0300", system: "Şasi", desc: "<strong>Rear Speed Sensor Malfunction</strong><br>Arka Hız Sensörü Arızası" },
    { code: "C0550", system: "ECU", desc: "<strong>ECU Malfunction</strong><br>Şasi Kontrol Ünitesi Dahili Hatası" },
    { code: "C0563", system: "ECU", desc: "<strong>Calibration ROM Checksum Error</strong><br>Kalibrasyon Hatası" },
    { code: "C0710", system: "Direksiyon", desc: "<strong>Steering Position Signal Malfunction</strong><br>Direksiyon Açı Sinyali Arızası" },
    { code: "C0750", system: "TPMS", desc: "<strong>Tire Pressure Monitor Sensor Not Transmitting</strong><br>Lastik Basınç Sensörü Sinyal Vermiyor" },

    // --- B Codes (Body / Gövde & Konfor) ---
    { code: "B0001", system: "Gövde", desc: "<strong>PCM Discrete Input Speed Signal Error</strong><br>PCM Hız Sinyali Hatası" },
    { code: "B0012", system: "Airbag", desc: "<strong>Right Front Passenger Airbag Deployment Loop</strong><br>Sağ Ön Yolcu Airbag Devresi" },
    { code: "B0022", system: "Airbag", desc: "<strong>Left Front Driver Airbag Deployment Loop Resistance Low</strong><br>Sürücü Airbag Direnci Düşük (Kısa Devre)" },
    { code: "B0028", system: "Airbag", desc: "<strong>Right Front Passenger Side Deployment Loop Resistance Low</strong><br>Sağ Yan Airbag Direnci Düşük" },
    { code: "B0040", system: "Airbag", desc: "<strong>Left Front Driver Side Deployment Loop Resistance Low</strong><br>Sol Yan Airbag Direnci Düşük" },
    { code: "B0051", system: "Airbag", desc: "<strong>Deployment Commanded</strong><br>Airbag Patlatma Komutu Verildi (Kaza Kaydı)" },
    { code: "B1000", system: "Gövde", desc: "<strong>ECU Malfunction</strong><br>Beyin Dahili Arıza" },
    { code: "B1276", system: "Klima", desc: "<strong>Servo Motor Potentiometer Foot Circuit Failure</strong><br>Ayak Bölgesi Havalandırma Motoru Hatası" },
    { code: "B1300", system: "Kapı", desc: "<strong>Power Door Lock Circuit Failure</strong><br>Merkezi Kilit Devresi Hatası" },
    { code: "B1318", system: "Akü", desc: "<strong>Battery Voltage Low</strong><br>Akü Voltajı Düşük" },
    { code: "B1325", system: "Kapı", desc: "<strong>Door Ajar Lamp Circuit Short To Battery</strong><br>Kapı Açık Lambası Kısa Devre" },
    { code: "B1342", system: "ECU", desc: "<strong>ECU Is Defective</strong><br>Beyin Arızalı" },
    { code: "B1352", system: "Ateşleme", desc: "<strong>Ignition Key-In Circuit Failure</strong><br>Kontak Anahtarı Takılı Uyarısı Hatası" },
    { code: "B1420", system: "Koltuk", desc: "<strong>Seat Switch Input Status</strong><br>Koltuk Düğmesi Giriş Hatası" },
    { code: "B1481", system: "Silecek", desc: "<strong>Wiper Washer Fluid Level Sensor Circuit Short To Battery</strong><br>Silecek Suyu Seviye Sensörü Hatası" },
    { code: "B2444", system: "Airbag", desc: "<strong>Driver Side Crash Sensor Internal Fault</strong><br>Sürücü Tarafı Kaza Sensörü Dahili Hata" },
    { code: "B2575", system: "Aydınlatma", desc: "<strong>Headlamp Control Circuit</strong><br>Far Kontrol Devresi" },

    // --- U Codes (Network / İletişim Hattı) ---
    { code: "U0001", system: "Network", desc: "<strong>High Speed CAN Communication Bus</strong><br>Yüksek Hız CAN Hattı Hatası" },
    { code: "U0010", system: "Network", desc: "<strong>Medium Speed CAN Communication Bus</strong><br>Orta Hız CAN Hattı Hatası" },
    { code: "U0028", system: "Network", desc: "<strong>Vehicle Communication Bus A</strong><br>Araç İletişim Hattı A" },
    { code: "U0073", system: "Network", desc: "<strong>Control Module Communication Bus Off</strong><br>Kontrol Modülü İletişim Hattı Kapalı" },
    { code: "U0100", system: "Network", desc: "<strong>Lost Communication With ECM/PCM A</strong><br>Motor Beyni (ECM/PCM) İle İletişim Kaybı" },
    { code: "U0101", system: "Network", desc: "<strong>Lost Communication with TCM</strong><br>Şanzıman Beyni (TCM) İle İletişim Kaybı" },
    { code: "U0103", system: "Network", desc: "<strong>Lost Communication With Gear Shift Module</strong><br>Vites Modülü İle İletişim Kaybı" },
    { code: "U0104", system: "Network", desc: "<strong>Lost Communication With Cruise Control Module</strong><br>Hız Sabitleyici İle İletişim Kaybı" },
    { code: "U0105", system: "Network", desc: "<strong>Lost Communication With Fuel Injector Control Module</strong><br>Enjektör Beyni İle İletişim Kaybı" },
    { code: "U0107", system: "Network", desc: "<strong>Lost Communication With Throttle Actuator Control Module</strong><br>Gaz Kelebeği Modülü İle İletişim Kaybı" },
    { code: "U0115", system: "Network", desc: "<strong>Lost Communication With ECM/PCM B</strong><br>Motor Beyni B İle İletişim Kaybı" },
    { code: "U0121", system: "Network", desc: "<strong>Lost Communication With Anti-Lock Brake System (ABS)</strong><br>ABS Beyni İle İletişim Kaybı" },
    { code: "U0122", system: "Network", desc: "<strong>Lost Communication With Vehicle Dynamics Control Module</strong><br>ESP/Denge Kontrol Modülü İle İletişim Kaybı" },
    { code: "U0126", system: "Network", desc: "<strong>Lost Communication With Steering Angle Sensor Module</strong><br>Direksiyon Açı Sensörü İle İletişim Kaybı" },
    { code: "U0127", system: "Network", desc: "<strong>Lost Communication With Tire Pressure Monitor Module</strong><br>Lastik Basınç Sensörü (TPMS) İle İletişim Kaybı" },
    { code: "U0128", system: "Network", desc: "<strong>Lost Communication With Park Brake Control Module</strong><br>El Freni Modülü İle İletişim Kaybı" },
    { code: "U0140", system: "Network", desc: "<strong>Lost Communication With Body Control Module</strong><br>Gövde Kontrol Modülü (BCM) İle İletişim Kaybı" },
    { code: "U0151", system: "Network", desc: "<strong>Lost Communication With Restraints Control Module</strong><br>Airbag Beyni İle İletişim Kaybı" },
    { code: "U0155", system: "Network", desc: "<strong>Lost Communication With Instrument Panel Cluster (IPC)</strong><br>Gösterge Paneli İle İletişim Kaybı" },
    { code: "U0164", system: "Network", desc: "<strong>Lost Communication With HVAC Control Module</strong><br>Klima Kontrol Modülü İle İletişim Kaybı" },
    { code: "U0184", system: "Network", desc: "<strong>Lost Communication With Radio</strong><br>Radyo İle İletişim Kaybı" },
    { code: "U0199", system: "Network", desc: "<strong>Lost Communication With Door Control Module A</strong><br>Kapı Kontrol Modülü A İle İletişim Kaybı" },
    { code: "U0212", system: "Network", desc: "<strong>Lost Communication With Steering Column Control Module</strong><br>Direksiyon Kolonu Modülü İle İletişim Kaybı" },
    { code: "U0230", system: "Network", desc: "<strong>Lost Communication With Rear Gate Module</strong><br>Bagaj Kapağı Modülü İle İletişim Kaybı" },
    { code: "U0300", system: "Network", desc: "<strong>Internal Control Module Software Incompatibility</strong><br>Modül Yazılım Uyumsuzluğu" },
    { code: "U0301", system: "Network", desc: "<strong>Software Incompatibility with ECM/PCM</strong><br>Motor Beyni Yazılım Uyumsuzluğu" },
    { code: "U0401", system: "Network", desc: "<strong>Invalid Data Received From ECM/PCM</strong><br>Motor Beyninden Geçersiz Veri Alındı" },
    { code: "U0402", system: "Network", desc: "<strong>Invalid Data Received From TCM</strong><br>Şanzıman Beyninden Geçersiz Veri Alındı" },
    { code: "U0415", system: "Network", desc: "<strong>Invalid Data Received From ABS Control Module</strong><br>ABS Beyninden Geçersiz Veri Alındı" },
    { code: "U0422", system: "Network", desc: "<strong>Invalid Data Received From Body Control Module</strong><br>BCM'den Geçersiz Veri Alındı" }
];
